export const DUMMY_PAWPALS = [
  {
    id: 1,
    pawpal: {
      id: 1,
      name: "Max",
      breed: "Golden Retriever",
      age: 2,
      photo: "https://images.dog.ceo/breeds/retriever-golden/joey_IMG_0261.jpg",
      gender: "Male",
      description: "A very friendly dog",
      owner: "John Doe",
    },
    wantedPartner: {
      breed: "Golden Retriever",
      age: 2,
      description: "A very strong dog",
    },
  },
  {
    id: 2,
    pawpal: {
      id: 2,
      name: "Luna",
      breed: "Labrador",
      age: 3,
      photo: "https://images.dog.ceo/breeds/labrador/n02099712_7683.jpg",
      gender: "Female",
      description: "Energetic and playful",
      owner: "Anna Smith",
    },
    wantedPartner: {
      breed: "Labrador",
      age: 2,
      description: "Loves swimming and outdoor activities",
    },
  },
  {
    id: 3,
    pawpal: {
      id: 3,
      name: "Rocky",
      breed: "German Shepherd",
      age: 4,
      photo: "https://images.dog.ceo/breeds/germanshepherd/n02106662_16149.jpg",
      gender: "Male",
      description: "Highly intelligent and loyal",
      owner: "Abraham Lincoln",
    },
    wantedPartner: {
      breed: "German Shepherd",
      age: 3,
      description: "Strong and protective",
    },
  },
  {
    id: 4,
    pawpal: {
      id: 4,
      name: "Bella",
      breed: "Poodle",
      age: 2,
      photo: "https://images.dog.ceo/breeds/poodle-toy/n02113624_213.jpg",
      gender: "Female",
      description: "Gentle and hypoallergenic",
      owner: "Dwight Schrute",
    },
    wantedPartner: {
      breed: "Poodle",
      age: 2,
      description: "Well-groomed and obedient",
    },
  },
  {
    id: 5,
    pawpal: {
      id: 5,
      name: "Charlie",
      breed: "Husky",
      age: 3,
      photo: "https://images.dog.ceo/breeds/husky/husky.jpg",
      gender: "Male",
      description: "Playful and loves outdoor adventures",
      owner: "Helen Keller",
    },
    wantedPartner: {
      breed: "Husky",
      age: 2,
      description: "Enjoys cold weather and sled pulling",
    },
  },
  {
    id: 6,
    pawpal: {
      id: 6,
      name: "Cupcake",
      breed: "Pitbull",
      age: 3,
      photo: "https://dogcrunch.com/wp-content/uploads/2021/11/Aggressive-Pitbull-Cover.jpg",
      gender: "Male",
      description: "Sweet and loves snuggling",
      owner: "Karen Smith",
    },
    wantedPartner: {
      breed: "Pitbull",
      age: 3,
      description: "Affectionate and good with kids",
    },
  },
  {
    id: 7,
    pawpal: {
      id: 7,
      name: "Bego",
      breed: "Bulldog",
      age: 2,
      photo: "https://images.dog.ceo/breeds/bulldog-english/murphy.jpg",
      gender: "Male",
      description: "Highly trainable and energetic",
      owner: "Luka Orjonikidze",
    },
    wantedPartner: {
      breed: "Bulldog",
      age: 2,
      description: "Active and loves herding",
    },
  },
];
export const DUMMY_INCOMING_PAWBOND_REQUESTS = [];
